# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Advokat Daniella
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

site_email: "<a href='ma&#105;l&#116;&#111;&#58;%64%6D%74&#64;advo&#107;a&#116;d&#97;n&#37;69&#101;l&#108;&#97;%2&#69;&#100;&#107;'>dmt&#64;a&#100;vokatdan&#105;&#101;lla&#46;&#100;k</a>"

exclude:      [
                'node_modules',
                'npm-debug.log',
                'package.json',
                'bower.json',
                'gulpfile.js',
                'Makefile',
                'composer.json',
                'composer.lock',
                'README.md',
                'Gemfile',
                'Gemfile.lock'
              ]

# Build settings
markdown: kramdown
